### ISSUE TITLE
Crashes the server when command report_handled is used.

### ISSUE THREAD

**Issue by DEPSTRCZ** [1Mack/CS2-CallAdmin#3]
`[All Chat][ItzDepstR (1011586979)]: !report_handled TGKTMMAFNW4FAXJ
[15:09:52.237] CSSharp: Native d01e4eb5 was invoked on a non-main thread
Unhandled exception. CounterStrikeSharp.API.Core.NativeException: Invoked on a non-main thread
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.GetSchemaValueByName[T](IntPtr instance, Int32 returntype, String classname, String propname) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1050
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetSchemaValue[T](IntPtr handle, String className, String propertyName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 75
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetString(IntPtr pointer, String className, String memberName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 133
   at CounterStrikeSharp.API.Core.CBasePlayerController.get_PlayerName() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 4697
   at CallAdmin.CallAdmin.ReportHandledCommand(CCSPlayerController player, CommandInfo command) in C:\Users\marcos\Documents\mack\csgo\cs2\CallAdmin\Commands.cs:line 148
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()`

server: version  : 1.39.7.8/13978 9842 secure  public
Metamod:Source version 2.0.0-dev+1271

**Comment by 1Mack** [comment]
Ty for your report. Download the new version -> https://github.com/1Mack/CS2-CallAdmin/releases/tag/V1.5
